[package]
name = "skia-canvas"
version = "0.9.25"
description = "A canvas environment for Node"
authors = ["Christian Swinehart <drafting@samizdat.co>"]
license = "MIT"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
crc = "1.8.1"
css-color = "0.1.1"
lazy_static = "1.4.0"
rayon = "1.5.1"

[dependencies.neon]
version = "0.10.0-alpha.2"
default-features = false
features = ["napi-6", "promise-api", "task-api"]

[dependencies.skia-safe]
version = "0.41.0"
features = ["textlayout"]
